In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('house_price.csv')

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [6]:
df.isnull().sum()[df.isnull().sum() > 0]

LotFrontage      259
Alley           1369
MasVnrType       872
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [10]:
df = df.drop(columns=['Alley', 'PoolQC', 'Fence', 'MiscFeature'])

In [11]:
df.isnull().sum()[df.isnull().sum() > 0]

LotFrontage     259
MasVnrType      872
MasVnrArea        8
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinType2     38
Electrical        1
FireplaceQu     690
GarageType       81
GarageYrBlt      81
GarageFinish     81
GarageQual       81
GarageCond       81
dtype: int64

In [12]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df

In [13]:
df=toldir(df)

In [16]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 77, dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=3:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [18]:
df=encodla(df)
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LandContour,LotConfig,Neighborhood,Condition1,...,MasVnrType_BrkFace,MasVnrType_Stone,CentralAir_N,CentralAir_Y,GarageFinish_Fin,GarageFinish_RFn,GarageFinish_Unf,PavedDrive_N,PavedDrive_P,PavedDrive_Y
0,1,60,3,65.0,8450,3,3,4,5,2,...,1,0,0,1,0,1,0,0,0,1
1,2,20,3,80.0,9600,3,3,2,24,1,...,1,0,0,1,0,1,0,0,0,1
2,3,60,3,68.0,11250,0,3,4,5,2,...,1,0,0,1,0,1,0,0,0,1
3,4,70,3,60.0,9550,0,3,0,6,2,...,1,0,0,1,0,0,1,0,0,1
4,5,60,3,84.0,14260,0,3,2,15,2,...,1,0,0,1,0,1,0,0,0,1

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
def scale(df):
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('SalePrice')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [21]:
df=scale(df)
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LandContour,LotConfig,Neighborhood,Condition1,...,MasVnrType_BrkFace,MasVnrType_Stone,CentralAir_N,CentralAir_Y,GarageFinish_Fin,GarageFinish_RFn,GarageFinish_Unf,PavedDrive_N,PavedDrive_P,PavedDrive_Y
0,0.000000,0.235294,0.75,0.150685,0.033420,1.0,1.0,1.0,0.208333,0.250,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.000685,0.000000,0.75,0.202055,0.038795,1.0,1.0,0.5,1.000000,0.125,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,0.001371,0.235294,0.75,0.160959,0.046507,0.0,1.0,1.0,0.208333,0.250,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.002056,0.294118,0.75,0.133562,0.038561,0.0,1.0,0.0,0.250000,0.250,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.002742,0.235294,0.75,0.215753,0.060576,0.0,1.0,0.5,0.625000,0.250,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [22]:
df['SalePrice']

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
x=df.drop('SalePrice',axis=1)
y=df['SalePrice']

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr

LinearRegression()

In [28]:
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

array([149053.31829422, 323665.82726632, 114060.36581912, 179200.74942916,
       321681.1126216 ,  67323.48092441, 238563.78659555, 144272.1718893 ,
        70362.76770761, 152138.45193664, 152795.38323875, 111050.27814524,
        68711.88726755, 212096.60195805, 163946.32833533, 137544.9266736 ,
       213960.50448953, 119667.09638702, 116637.28298502, 233833.13671802,
       132474.95200363, 211111.58560926, 190237.7634607 , 122239.1868816 ,
       219726.09617192, 158464.24515313, 209801.76017648,  71388.61653274,
       164609.87970066, 195530.17318144, 161951.76501803, 257091.95830907,
       190971.73640568,  97547.80770532, 254511.83080831, 143639.45904612,
       130895.16892602, 215812.64190436, 287325.39693535,  93893.94861353,
       122848.61696797, 253262.83366706, 107595.8139392 , 320527.65428019,
       130906.93731224, 152237.22804597,  97750.07543899, 133382.17660062,
       381984.57343668, 132946.50479435, 111647.85379218, 222625.59037839,
       100068.9395314 , 355095.33230237, 156248.58507757, 242884.58906193,
       228563.59905295, 186431.65610952, 127544.47823515,  97586.53200688,
        29904.29737412, 155735.5423594 , 306288.82345027, 264869.11938546,
       286129.77521544, 219454.43441794, 104196.13388604, 308193.24365248,
       108192.77700356, 180108.71728202, 113790.79082922, 130793.03365976,
        92941.60388345,  63482.15630463, 408247.95601502, 167359.85500387,
       279694.58637683, 284896.64670662, 138283.62716934, 106647.8675279 ,
       123829.66861992,  66344.15232422, 123344.84928242, 126968.21835516,
       167349.41684994, 133240.59536259, 259122.22024844, 207850.0442653 ,
       155360.60284082, 195113.21198295, 126785.25831977, 128195.72990973,
       122736.91235699, 273099.69977019, 106351.73650764, 189901.92822611,
       196923.89191161, 198895.59082139, 209126.54998351, 283715.88620239,
       183832.34301405, 219289.9916647 , 286316.85170996, 127753.65286417,
       189174.53689806, 182400.50420487, 160733.29572733, 251086.17570905,
       130850.78522728, 223228.4399369 ,  30313.50805826, 121131.88803239,
       135331.22915171, 113710.04137104, 220247.83414154, 131224.42484682,
        92235.89496404, 111379.13313282, 152188.28656099, 262629.85817137,
       143183.52805529, 157199.93173552, 176794.72834977, 177320.58802969,
       192069.58092922, 137566.22930423, 234430.68834125,  83896.64900326,
       136286.1297298 , 195120.60796621, 192665.80258673, 327246.54680624,
       197696.8251992 , 120154.80833426,  57892.58964217, 355820.92272394,
       337730.48777845, 140936.55345977, 235979.73108238, 523764.22890719,
       302699.65442306, 126783.32811442, 200045.65615231, 154677.6367964 ,
       101386.31016973, 113658.84345692, 230235.72897589, 194858.70979605,
       107004.13822953,  52689.28724872, 119299.90202857, 147852.60081822,
       206205.74954713, 164770.56031844,  48374.18437191, 112889.19972092,
       134284.93428501, 142066.96758438,  81680.87973265, 141036.42402758,
       227780.0158142 , 124728.72428395, 275183.48128382, 165628.46308428,
       104032.58455715, 105623.65319357, 273604.76394265, 329739.55619402,
       385949.29554781, 213622.54688839, 348277.48772816,  78967.87997723,
        95908.24741164, 161255.68330381, 296837.71350817, 105194.97734942,
       120400.41354041, 240123.24696754, 121233.97994329, 163784.28247266,
       157769.13383637, 142425.45110358, 117334.10719759, 142764.94945867,
       249197.75603078, 165897.92278467, 278779.97081267, 229381.77791317,
       192751.44879974,  75122.13534147, 107314.10962469,  97791.65288951,
        99470.47297699, 133746.62215066, 208272.95278699, 209995.7089168 ,
       212032.60874583,  85133.93407386, 229542.78113609, 119530.46176018,
       289290.25468234, 190213.00974637,  93066.16899896, 291741.8767441 ,
       204357.28741239, 108853.83708971, 235639.39334812, 126364.19740238,
       147150.72263639,  95187.43929741, 258593.6497666 , 153125.26413666,
       109790.39771928, 166584.12284724, 217825.75405864, 253121.41178179,
       219698.87021359, 130683.37007587, 104023.92949635, 143838.75130184,
       146879.41240854, 219971.41320426, 197562.78104095,  92730.50230078,
       236087.96764184, 150875.58200774,  93311.82691702,  75665.33510855,
       184579.63791534, 110511.64906745,  94756.29250463, 185926.9753334 ,
       130503.61200409, 111022.29866804, 248741.72992037, 131362.37358788,
       204169.65465361, 170917.95702161, 269739.29696469, 115038.69859222,
       114285.47148044, 300345.45067617, 234520.60328038, 397613.13028194,
       202670.80014228, 104740.05678199, 160783.8958559 , 192824.3066258 ,
       138453.65162991,  91673.9233239 , 186313.90767445, 192212.2866243 ,
       131910.07882878, 120344.01213917, 150887.32939831, 134073.95827839,
       110920.58447107, 107784.56751938, 189367.52050392, 249405.68747767,
       282563.52421325, 189408.77644521, 119544.83293594, 253847.12284368,
       337563.1132718 , 234497.10542242, 184992.67795449, 149863.98936478,
       110462.41130441, 173086.88892583, 351617.02581071, 208197.71213205,
       231149.88832395,  77742.58651523,  92757.90807427, 132096.2114768 ,
       157198.2169498 , 301493.34751924, 245093.55602304, 135354.49439777,
       213802.23525508, 108627.19360727, 194952.27156609, 112532.25545693,
       295851.55197093, 186919.59620475, 209798.12317762, 123729.34409766,
       278534.02499008, 217753.70418543, 109951.50158221, 101891.74079528])

In [30]:
from sklearn.metrics import mean_absolute_error,r2_score
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [31]:
print('mae=',mae)
print('r2=',r2)

mae= 21373.28220065416
r2= 0.8500950270735168

In [32]:
from sklearn.model_selection import KFold,cross_val_score

In [33]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [34]:
scores=cross_val_score(lr,x,y,cv=kf,scoring='r2')

In [35]:
print(scores)

[0.85009503 0.81257494 0.37627552 0.85528412 0.90199571]

In [36]:
for i in scores:
    print(i)

0.8500950270735168
0.8125749381209859
0.37627552351815663
0.8552841214795888
0.9019957064317244

In [38]:
import numpy as np

In [40]:
np.mean(scores)

np.float64(0.7592450633247945)

In [41]:
np.std(scores)

np.float64(0.19357928953136058)

In [42]:
from sklearn.metrics import make_scorer

In [43]:
mae=make_scorer(mean_absolute_error,greater_is_better=False)

In [44]:
scores=cross_val_score(lr,x,y,cv=kf,scoring=mae)

In [47]:
print(-scores.mean())

20625.575840130048