In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('healthcare-dataset-stroke-data.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   str
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   str
 6   work_type          5110 non-null   str
 7   Residence_type     5110 non-null   str
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   str
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), str(5)
memory usage: 479.2 KB

In [5]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [6]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [7]:
df=df.drop('bmi',axis=1)
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
smoking_status       0
stroke               0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=3:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [9]:
df=encodla(df)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    5110 non-null   int64
 1   age                   5110 non-null   float64
 2   hypertension          5110 non-null   int64
 3   heart_disease         5110 non-null   int64
 4   work_type             5110 non-null   int64
 5   avg_glucose_level     5110 non-null   float64
 6   smoking_status        5110 non-null   int64
 7   stroke                5110 non-null   int64
 8   gender_Female         5110 non-null   int64
 9   gender_Male           5110 non-null   int64
 10  gender_Other          5110 non-null   int64
 11  ever_married_No       5110 non-null   int64
 12  ever_married_Yes      5110 non-null   int64
 13  Residence_type_Rural  5110 non-null   int64
 14  Residence_type_Urban  5110 non-null   int64
dtypes: float64(2), int64(13)
memory usage: 599.0 KB

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
def scale(df):
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('stroke')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [12]:
df=scale(df)

In [13]:
df.head()

,id,age,hypertension,heart_disease,work_type,avg_glucose_level,smoking_status,stroke,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,Residence_type_Rural,Residence_type_Urban
0,0.123214,0.816895,0.0,1.0,0.50,0.801265,0.333333,1,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1,0.708205,0.743652,0.0,0.0,0.75,0.679023,0.666667,1,1.0,0.0,0.0,0.0,1.0,1.0,0.0
2,0.426015,0.975586,0.0,1.0,0.50,0.234512,0.666667,1,0.0,1.0,0.0,0.0,1.0,1.0,0.0
3,0.824928,0.597168,0.0,0.0,0.50,0.536008,1.000000,1,1.0,0.0,0.0,0.0,1.0,0.0,1.0
4,0.021929,0.963379,1.0,0.0,0.75,0.549349,0.666667,1,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [14]:
from sklearn.model_selection import train_test_split
x=df.drop('stroke',axis=1)
y=df['stroke']

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr

LogisticRegression()

In [17]:
lr.fit(x_train,y_train)

LogisticRegression()

In [18]:
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(1022,))

In [19]:
from sklearn.metrics import accuracy_score,classification_report

In [20]:
acc_score=accuracy_score(y_pred,y_test)
acc_score

0.9393346379647749

In [21]:
report=classification_report(y_test,y_pred)
classification_report

c:\Users\Fazliddin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Fazliddin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Fazliddin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [22]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(lr,x,y,cv=kf,scoring='accuracy')
print(scores)

[0.93933464 0.94911937 0.96183953 0.9481409  0.95792564]

In [23]:
import numpy as np
np.mean(scores)

np.float64(0.9512720156555773)

Decision tree

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()

In [25]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [26]:
y_pred=dtc.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(1022,))

In [27]:
dtcscore=accuracy_score(y_test,y_pred)
print(dtcscore)

0.9090019569471625

In [31]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(dtc,x,y,cv=kf,scoring='accuracy')
print(scores)

[0.91193738 0.90900196 0.90802348 0.90998043 0.9109589 ]

In [32]:
import numpy as np
np.mean(scores)

np.float64(0.9099804305283756)

In [33]:
 %pip install tabulate

Requirement already satisfied: tabulate in c:\users\fazliddin\appdata\local\programs\python\python311\lib\site-packages (0.10.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
from tabulate import tabulate

In [35]:
results=[
['Logistic Regression',0.951],
['Decision Tree classifier',0.909],
]


headers=['Algorithm','Accuracy_score']

table=tabulate(results, headers=headers, tablefmt='grid',floatfmt='.2f')

print(table)

+--------------------------+------------------+
| Algorithm                |   Accuracy_score |
+==========================+==================+
| Logistic Regression      |             0.95 |
+--------------------------+------------------+
| Decision Tree classifier |             0.91 |
+--------------------------+------------------+

In [36]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()

In [37]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [38]:
y_pred=dtr.predict(x_test)
y_pred

array([0., 0., 0., ..., 1., 1., 0.], shape=(1022,))

In [40]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [41]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [42]:
print(r2)
print(mae)
print(mse)

-0.5281922043010758
0.08708414872798434
0.08708414872798434

In [45]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(dtr,x,y,cv=kf,scoring='r2')
print(scores)

[-0.51102151 -0.90459952 -1.29261549 -0.77109255 -1.25778559]