In [56]:
import pandas as pd

In [57]:
df=pd.read_csv('appearances.csv')

In [58]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           str
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    str
 6   player_name             str
 7   competition_id          str
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), str(4)
memory usage: 169.3 MB

In [60]:
df.isnull().sum()

appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
player_name               6
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

Missing qiymatlar yo'q shuning uchun keyingi bosqichga o'tamiz

In [61]:
from sklearn.preprocessing import LabelEncoder
def encod(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<4:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df[col].drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [62]:
df=encod(df)

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           int64
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    int64
 6   player_name             int64
 7   competition_id          int64
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(13)
memory usage: 169.3 MB

In [64]:
from sklearn.preprocessing import MinMaxScaler
def scale(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64']).columns.drop('goals')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [65]:
df=scale(df)

In [66]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.032631,0.008627,0.027515,0.007724,0.002140,0.000000,0.106320,0.142857,0.0,0.0,2,0.000000,0.605442
1,0.032658,0.009377,0.057371,0.080144,0.024469,0.000268,0.816157,0.309524,0.0,0.0,0,0.000000,0.605442
2,0.032678,0.009658,0.030982,0.056663,0.004225,0.000268,0.833260,0.309524,0.0,0.0,0,0.000000,0.299320
3,0.032679,0.009660,0.053099,0.011541,0.060261,0.000268,0.936956,0.309524,0.0,0.0,0,0.000000,0.605442
4,0.032679,0.009662,0.088351,0.001759,0.027279,0.000268,0.609204,0.309524,0.0,0.0,0,0.166667,0.605442

In [68]:
from sklearn.model_selection import train_test_split
x=df.drop('goals',axis=1)
y=df['goals']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [69]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr

LogisticRegression()

In [70]:
lr.fit(x_train,y_train)

LogisticRegression()

In [71]:
y_pred=lr.predict(x_test)
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
from sklearn.metrics import accuracy_score,classification_report
score=accuracy_score(y_test,y_pred)
print(score)
print(classification_report(y_test, y_pred))

0.9134350044820454
              precision    recall  f1-score   support

           0       0.91      1.00      0.95    311810
           1       0.75      0.00      0.00     26373
           2       0.00      0.00      0.00      2820
           3       0.00      0.00      0.00       328
           4       0.00      0.00      0.00        28
           5       0.00      0.00      0.00         3

    accuracy                           0.91    341362
   macro avg       0.28      0.17      0.16    341362
weighted avg       0.89      0.91      0.87    341362

c:\Users\Fazliddin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Fazliddin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Fazliddin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [39]:
df2=df

In [40]:
df2.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.032631,0.008627,0.027515,0.007724,0.002140,0.000000,0.106320,0.142857,0.0,0.0,2,0.000000,0.605442
1,0.032658,0.009377,0.057371,0.080144,0.024469,0.000268,0.816157,0.309524,0.0,0.0,0,0.000000,0.605442
2,0.032678,0.009658,0.030982,0.056663,0.004225,0.000268,0.833260,0.309524,0.0,0.0,0,0.000000,0.299320
3,0.032679,0.009660,0.053099,0.011541,0.060261,0.000268,0.936956,0.309524,0.0,0.0,0,0.000000,0.605442
4,0.032679,0.009662,0.088351,0.001759,0.027279,0.000268,0.609204,0.309524,0.0,0.0,0,0.166667,0.605442

In [47]:
from sklearn.model_selection import train_test_split
x=df2.drop('goals',axis=1)
y=df2['goals']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr

LinearRegression()

In [49]:
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

array([0.06812695, 0.11205037, 0.19233379, ..., 0.05149805, 0.05212609,
       0.1101925 ], shape=(341362,))

In [50]:
from sklearn.metrics import r2_score,mean_absolute_error
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
print(r2)
print(mae)

0.011167915340180246
0.1740857467133916