In [44]:
import pandas as pd

In [45]:
df=pd.read_csv('appearances.csv')

In [46]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [47]:
df.isnull().sum()

appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
player_name               6
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

In [48]:
df=df.drop('player_name',axis=1)

In [49]:
df = df.drop(columns=['appearance_id'])

In [50]:
df.isnull().sum()

game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   game_id                 int64
 1   player_id               int64
 2   player_club_id          int64
 3   player_current_club_id  int64
 4   date                    str
 5   competition_id          str
 6   yellow_cards            int64
 7   red_cards               int64
 8   goals                   int64
 9   assists                 int64
 10  minutes_played          int64
dtypes: int64(9), str(2)
memory usage: 143.2 MB

In [58]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [59]:
df=encodla(df)

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   game_id                 int64
 1   player_id               int64
 2   player_club_id          int64
 3   player_current_club_id  int64
 4   date                    int64
 5   competition_id          int64
 6   yellow_cards            int64
 7   red_cards               int64
 8   goals                   int64
 9   assists                 int64
 10  minutes_played          int64
dtypes: int64(11)
memory usage: 143.2 MB

In [63]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
def scale(df):
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('goals')
    df[num_col]=scaler.fit_transform(df[num_col])
    return(df)

In [64]:
df=scale(df)

In [65]:
df.head()

,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.008627,0.027515,0.007724,0.002140,0.000000,0.142857,0.0,0.0,2,0.000000,0.605442
1,0.009377,0.057371,0.080144,0.024469,0.000268,0.309524,0.0,0.0,0,0.000000,0.605442
2,0.009658,0.030982,0.056663,0.004225,0.000268,0.309524,0.0,0.0,0,0.000000,0.299320
3,0.009660,0.053099,0.011541,0.060261,0.000268,0.309524,0.0,0.0,0,0.000000,0.605442
4,0.009662,0.088351,0.001759,0.027279,0.000268,0.309524,0.0,0.0,0,0.166667,0.605442

In [67]:
from sklearn.model_selection import train_test_split
x=df.drop('goals',axis=1)

In [69]:
y=df['goals']

In [70]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [71]:
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
dtr=DecisionTreeRegressor()

In [72]:
dtr

DecisionTreeRegressor()

In [73]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [75]:
y_pred=dtr.predict(x_test)

In [76]:
y_pred

array([0., 1., 0., ..., 0., 0., 0.], shape=(341362,))

In [77]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [78]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [79]:
print('r2=',r2)
print('mae=',mae)
print('mse=',mse)
print('rmse',rmse)

r2= -0.8730637677664048
mae= 0.16999255921865938
mse= 0.20803428618299635
rmse 0.45610775720546165

Decision tree classifier

In [80]:
dtc=DecisionTreeClassifier()
dtc

DecisionTreeClassifier()

In [81]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [82]:
y_pred=dtc.predict(x_test)

In [83]:
y_pred

array([0, 1, 0, ..., 0, 0, 0], shape=(341362,))

In [85]:
from sklearn.metrics import classification_report

In [86]:
cr=classification_report(y_test,y_pred)

In [87]:
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.91      0.92    311810
           1       0.14      0.15      0.14     26373
           2       0.03      0.04      0.04      2820
           3       0.03      0.03      0.03       328
           4       0.00      0.00      0.00        28
           5       0.00      0.00      0.00         3

    accuracy                           0.85    341362
   macro avg       0.19      0.19      0.19    341362
weighted avg       0.85      0.85      0.85    341362

Linear Regression

In [89]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr

LinearRegression()

In [90]:
lr.fit(x_train,y_train)

LinearRegression()

In [91]:
y_pred=lr.predict(x_test)

In [92]:
print(y_pred)

[0.06674831 0.11148363 0.1902015  ... 0.0517319  0.05252962 0.11366615]

In [93]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [94]:
print('r2=',r2)
print('mae=',mae)
print('mse=',mse)
print('rmse=',rmse)

r2= 0.011146944648449897
mae= 0.17408812657964068
mse= 0.10982826268389495
rmse= 0.3314034741578533

Logistic Regression

In [95]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr

LogisticRegression()

In [96]:
lr.fit(x_train,y_train)

LogisticRegression()

In [97]:
y_pred=lr.predict(x_test)

In [98]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(341362,))

In [99]:
from sklearn.metrics import accuracy_score

In [100]:
acc_score=accuracy_score(y_test,y_pred)

In [101]:
acc_score

0.9134350044820454